---
title       : Some Mathematical Formulaes
subtitle    : Formulaes of finding Area of triangle, Surface Areas and Volumes of Cuboid, Cube, Sphere, Hemisphere, Cylinder and Cone
author      : Nidhi Shrivastava
job         : FreeLance
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---

## About this presentation

```This presentation consists of some Mathematical Formulaes which is useful for all grades of school.

```--- .class #id 

## Linear Form of Equation

The general linear form of equation is $$ax+by+c=0$$ of first degree.

## Quadratic form of Eqaution

The general form of quadratic equation is $$ ax^2+bx+c=0 $$ which is also a polynomial of degree 2.

## Area of triangle

Area of triangle with its sides a, b, c is calculated by using Heron's formula,

Area of triangle =    $$ \sqrt (s(s - a)(s - b)(s - c) $$ where 
                       s = $$\frac{ a + b + c}{2}$$
                       
Area of quadrilateral whose sides and one diagonal are given, can be calculated by dividing the quadrilateral into two triangles and using Heron's Formula.

##Surface Areas and Volumes

**Surface Area of Cuboid** =    $$ 2(lb + bh + lh) $$ , * where $l$, $b$, $h$ are the length, breadth, height of a cuboid.*


**Volume of a cuboid** = $$ l*b*h $$ , where $l$, $b$, $h$ are the length, breadth, height of a cuboid.

##Surface Areas and Volumes

**Surface Area of a cube** = $$ 6  a^2, $$,  where $a$ is a side of a cube 


**Volume of a cube** = $$\ a ^ 3 $$, where $a$ is side of a cube.

##Surface Areas and Volumes

**Curved Surface Area of a cylinder** =$$ 2\ \pi\ r\ h $$,  *where $r$ is the radius and $h$ is the height of the cylinder.* 


**Total Surface Area of a cylinder **= $$ 2 \pi r (r+h) $$, where $r$ is the radius and $h$ is the height of the cylinder.

**Volume of a cylinder**= $$\pi r^2 h$$, where r is the radius and h is the height of the cylinder

##Surface Areas and Volumes

**Curved Surface Area of a cone**=$$\pi r l$$, Where $r$ is the radius and $l$ is the slant height of the cone.

**Total Surface Area of a right circular cone** = $$\pi r (l+r)$$ or $$\pi r^2 + \pi r l $$ where $l$ is the slant height and $r$ is the radius of the cone.

Volume of a cone =$$\frac{1}{3} \pi r^2 h$$ where $r$ is the radius and $h$ is the height of the cone.


##Surface Areas and Volumes

**Surface Area of a sphere**= $$ 4 \pi r^2$$, where $r$ is the radius of the sphere.

**Volume of a sphere**=$$ \frac{4}{3} \pi r^3 $$, where $r$ is the radius of the sphere.


##Surface Areas and Volumes


**Curved Surface Area of a hemisphere** = $$2 \pi r^2$$, where $r$ is the radius of the hemisphere.

**Total Surface Area of the hemisphere**=$$ 3 \pi r^2$$, where $r$ is the radius of the hemisphere.

**Volume of a hemisphere**=$$\frac{2}{3} \pi r^3$$, where $r$ is the radius of the hemisphere.



